### ISSUE TITLE
Update example to say mycompany.my.centrify.net

### ISSUE THREAD

**Issue by harvey-kwok** [centrify/centrifycli#6]
After Idaptive spin out, the example should use mycompany.my.centrify.net instead of mycompany.my.centrify.com

**Comment by nate-yocom** [comment]
If you mean the text here: https://github.com/centrify/centrifycli/wiki/Centrify-CLI:-Centrify-Command-Line-Interface - this is done.  If you mean somewhere else, please be more specific ;).

**Comment by harvey-kwok** [comment]
I meant [here](https://github.com/centrify/centrifycli/blob/5a9babb806410155687c1eb60caff78fce954581/CentrifyCLI.cs#L48)

**Comment by nate-yocom** [comment]
fixed - https://github.com/centrify/centrifycli/commit/a7b133f13041d0ba5d9c388c12c7bf48b68a8b11 (i used wrong issue #, oops).
